export { default as HeroSection } from './HeroSection'
export { default as AboutSection } from './AboutSection'
export { default as StorySection } from './StorySection'
export { default as ProjectsSection } from './ProjectsSection'
export { default as CertificatesSection } from './CertificatesSection'
export { default as ServicesSection } from './ServicesSection'
export { default as ContactSection } from './ContactSection'
